# Generated by Django 4.2.30 on 2026-09-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_awarded', models.DecimalField(decimal_places=2, help_text='Nilai yang diberikan juri', max_digits=6)),
                ('feedback', models.TextField(blank=True, help_text='Catatan atau feedback juri')),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('attempt_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_evaluations', to='attempts.attemptanswer')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Essay Evaluation',
                'verbose_name_plural': 'Essay Evaluations',
                'db_table': 'quiz_essay_evaluations',
            },
        ),
        migrations.CreateModel(
            name='AttemptGrade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mcq_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Total nilai pilihan ganda dari auto-scoring', max_digits=7)),
                ('essay_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Total nilai essay dari juri', max_digits=7)),
                ('total_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Total skor gabungan', max_digits=7)),
                ('is_finalized', models.BooleanField(default=False, help_text='Status finalisasi nilai oleh organizer/panitia')),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='attempts.examattempt')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attempt Grade',
                'verbose_name_plural': 'Attempt Grades',
                'db_table': 'quiz_attempt_grades',
                'ordering': ['-total_score'],
            },
        ),
        migrations.AddConstraint(
            model_name='essayevaluation',
            constraint=models.UniqueConstraint(fields=('attempt_answer', 'judge'), name='unique_judge_evaluation_per_answer'),
        ),
    ]
