# Generated by Django 6.1.1 on 2026-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayevaluation',
            name='dispute_reason',
            field=models.CharField(blank=True, default='', help_text='Alasan eskalasi / sengketa penilaian', max_length=255),
        ),
        migrations.AddField(
            model_name='essayevaluation',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Catatan rahasia dewan juri / deliberasi internal (hanya juri & panitia)'),
        ),
        migrations.AddField(
            model_name='essayevaluation',
            name='is_flagged_for_review',
            field=models.BooleanField(default=False, help_text='Tandai jika jawaban perlu didiskusikan / dieskalasi ke juri kepala'),
        ),
        migrations.AlterField(
            model_name='essayevaluation',
            name='feedback',
            field=models.TextField(blank=True, help_text='Catatan atau feedback juri (dapat dilihat oleh peserta jika diizinkan)'),
        ),
    ]
