# Generated by Django 6.1.1 on 2026-09-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DEVELOPER', 'Lead Developer / DevSecOps'), ('SUPER_ADMIN', 'Super Admin'), ('ORGANIZER', 'Organizer'), ('AUTHOR', 'Question Author'), ('REVIEWER', 'Reviewer'), ('JUDGE', 'Judge'), ('PARTICIPANT', 'Participant'), ('AUDITOR', 'Auditor / Observer')], db_index=True, default='PARTICIPANT', help_text='Peran pengguna dalam ekosistem lomba.', max_length=20),
        ),
    ]
