# Generated by Django 4.2.30 on 2026-09-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField(help_text='Jadwal kompetisi mulai dibuka')),
                ('end_time', models.DateTimeField(help_text='Batas waktu kompetisi berakhir')),
                ('duration_minutes', models.PositiveIntegerField(default=90, help_text='Durasi pengerjaan per attempt dalam menit')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published (Akan Datang)'), ('FROZEN', 'Frozen (Soal Dikunci)'), ('OPEN', 'Open (Sedang Berlangsung)'), ('CLOSED', 'Closed (Selesai)'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('max_attempts', models.PositiveIntegerField(default=1, help_text='Jumlah maksimal attempt yang diizinkan per peserta')),
                ('is_randomized_questions', models.BooleanField(default=False, help_text='Acak urutan soal untuk setiap peserta')),
                ('is_randomized_options', models.BooleanField(default=False, help_text='Acak pilihan jawaban MCQ untuk setiap peserta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_competitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'quiz_competitions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_disqualified', models.BooleanField(default=False)),
                ('disqualification_reason', models.TextField(blank=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_participant_enrollments',
            },
        ),
        migrations.AddConstraint(
            model_name='participantenrollment',
            constraint=models.UniqueConstraint(fields=('competition', 'participant'), name='unique_participant_per_competition'),
        ),
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='check_competition_end_after_start'),
        ),
    ]
