# Generated by Django 4.2.30 on 2026-09-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('start_time', models.DateTimeField(help_text='Timestamp server saat peserta menekan Mulai Ujian')),
                ('server_deadline', models.DateTimeField(help_text='Batas waktu absolut pengerjaan yang ditegakkan server')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('AUTO_SUBMITTED', 'Auto Submitted'), ('DISQUALIFIED', 'Disqualified')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='competitions.competition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Attempt',
                'verbose_name_plural': 'Exam Attempts',
                'db_table': 'quiz_exam_attempts',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('essay_text', models.TextField(blank=True, default='')),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('revision_count', models.PositiveIntegerField(default=1)),
                ('is_flagged_for_review', models.BooleanField(default=False, help_text='Penanda ragu-ragu oleh peserta')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='attempts.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_answers', to='questions.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_answers', to='questions.questionoption')),
            ],
            options={
                'verbose_name': 'Attempt Answer',
                'verbose_name_plural': 'Attempt Answers',
                'db_table': 'quiz_attempt_answers',
            },
        ),
        migrations.CreateModel(
            name='AnswerHistoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_id', models.UUIDField(blank=True, null=True)),
                ('essay_text', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField()),
                ('attempt_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='attempts.attemptanswer')),
            ],
            options={
                'verbose_name': 'Answer History Log',
                'verbose_name_plural': 'Answer History Logs',
                'db_table': 'quiz_answer_history_logs',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['participant', 'status'], name='quiz_exam_a_partici_0d6bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['competition', 'status'], name='quiz_exam_a_competi_5dd205_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('competition', 'participant', 'attempt_number'), name='unique_attempt_per_number'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_answer_per_attempt_question'),
        ),
    ]
