# Generated by Django 4.2.30 on 2026-09-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MCQ', 'Pilihan Ganda'), ('ESSAY', 'Essay')], db_index=True, default='MCQ', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Konten soal (mendukung formatting teks/markdown)')),
                ('points', models.DecimalField(decimal_places=2, default=10.0, help_text='Bobot nilai soal', max_digits=6)),
                ('sequence', models.PositiveIntegerField(default=1, help_text='Urutan tampilan default soal')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('INVALIDATED', 'Invalidated (Dibatalkan)')], db_index=True, default='DRAFT', max_length=15)),
                ('version', models.PositiveIntegerField(default=1, help_text='Nomor versi soal jika terjadi revisi sebelum kuis freeze')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='competitions.competition')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'quiz_questions',
                'ordering': ['competition', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False, help_text='Kunci jawaban benar (DILINDUNGI DARI CLIENT)')),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'verbose_name': 'Question Option',
                'verbose_name_plural': 'Question Options',
                'db_table': 'quiz_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='File challenge yang disimpan di quarantine sandbox', upload_to='quarantine/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('display_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('file_size', models.BigIntegerField(help_text='Ukuran file dalam bytes')),
                ('sha256_hash', models.CharField(help_text='SHA-256 integrity checksum', max_length=64)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='questions.question')),
            ],
            options={
                'verbose_name': 'Question Attachment',
                'verbose_name_plural': 'Question Attachments',
                'db_table': 'quiz_question_attachments',
            },
        ),
        migrations.CreateModel(
            name='AttachmentDownloadToken',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='questions.questionattachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quiz_attachment_tokens',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['competition', 'status'], name='quiz_questi_competi_625645_idx'),
        ),
        migrations.AddIndex(
            model_name='attachmentdownloadtoken',
            index=models.Index(fields=['token', 'expires_at', 'is_used'], name='quiz_attach_token_54b1fe_idx'),
        ),
    ]
