# Generated by Django 6.1.1 on 2026-09-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rubric_guidelines',
            field=models.TextField(blank=True, default='', help_text='Pedoman rubrik penilaian, poin kunci eksploitasi, dan kunci jawaban bagi dewan juri'),
        ),
    ]
