# Generated by Django 4.2.30 on 2026-09-11 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('START_EXAM', 'Start Exam Attempt'), ('AUTOSAVE_ANSWER', 'Autosave Answer'), ('FINAL_SUBMIT', 'Final Submit Exam'), ('DOWNLOAD_ATTACHMENT', 'Download Challenge Attachment'), ('QUESTION_CREATE', 'Create Question'), ('QUESTION_UPDATE', 'Update Question'), ('QUESTION_INVALIDATE', 'Invalidate Question'), ('GRADE_ESSAY', 'Grade Essay Answer'), ('FINALIZE_SCORE', 'Finalize Score'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity Detected')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(default=dict, help_text='Metadata terstruktur seputar aksi (IDs, hash, previous values, delta)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'db_table': 'quiz_security_audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='quiz_securi_event_t_caa83b_idx'), models.Index(fields=['user', 'event_type'], name='quiz_securi_user_id_cb0aba_idx')],
            },
        ),
    ]
